### ISSUE TITLE
[Feature] 산 상세 정보 조회 기능 구현

### ISSUE THREAD

**Issue by lhs8701** [ORGO-Official/orgo-backend#16]
## 💡 Description
> 이슈의 목적을 간단히 소개해주세요

사용자가 등산 인증을 하기에 앞서, 등산할 산을 선택할 수 있도록 정보 조회 기능을 구현합니다. 

## ✅ To-do
> 이슈에서 할 일을 적어주세요

- [x] 더미데이터 초기화 
- [x] 산 정보 테이블 생성
- [x] 특징 태그 테이블 생성
- [x] 산 상세 정보 조회 기능 구현
  - 산 이름
  - 주소
  - 위도
  - 경도
  - 고도 
  - 난이도(1, 2, 3)
  - 전화번호 
  - 특징 태그

## 🗨️ ETC
> 기타 및 참고 사항을 적어주세요

OOO
