### ISSUE TITLE
[Feature] Custom Exception 처리

### ISSUE THREAD

**Issue by lhs8701** [ORGO-Official/orgo-backend#26]
## 💡 Description
> 이슈의 목적을 간단히 소개해주세요

클라이언트에 적절한 예외를 던지기 위해, Custom Exception을 생성하고, 처리하는 로직을 구현합니다. 

## ✅ To-do
> 이슈에서 할 일을 적어주세요

- [x] ErrorCode 정의
- [x] CustomException 부모 클래스 정의
- [x] ExceptionAdvice 정의 
- [x] 기존 RuntimeException을 CustomException으로 대체 
- [x] 시큐리티 필터단에서 발생하는 Exception 처리
  - [x] UserNotFoundException
  - [x] CustomJwtException

## 🗨️ ETC
> 기타 및 참고 사항을 적어주세요

OOO
