### ISSUE TITLE
[Feature] 이미지 처리 

### ISSUE THREAD

**Issue by lhs8701** [ORGO-Official/orgo-backend#31]
## 💡 Description
> 이슈의 목적을 간단히 소개해주세요

프로필 이미지를 업로드할 수 있도록 이미지 처리를 구현합니다. 

## ✅ To-do
> 이슈에서 할 일을 적어주세요

- [x] 이미지 업로드 구현
- [x] 이미지 삭제 구현
- [ ] 회원가입 시, 기본 프로필 이미지 설정

## 🗨️ ETC
> 기타 및 참고 사항을 적어주세요

OOO
