### ISSUE TITLE
[Refactor] 완등 기록 조회 API 수정 및 코드 리팩토링

### ISSUE THREAD

**Issue by devMuscle** [ORGO-Official/orgo-backend#44]
## 💡 Description
완등 기록 조회 API 반환 값에 고도, 횟수 추가
코드 리뷰시 지적 받았던 부분 및 전반적인 코드 리팩토링

## ✅ To-do
- [x] 완등 기록 조회 API 반환 값에 고도, 횟수 추가
- [x] URL에 "climbingrecords" 를 하이픈을 사용하여 "climbing-records"로 변경
- [ ] ClimbingRecordController에서 CustomException으로 변경 및 Exception handler로 예외 처리 변경
- [x] ClimbingRecordService에서 else 문 제거
- [x] ClimbingRecordService의 viewMyClimbingRecords 메서드에서 회원이 없을시 UserNotFoundException 발생
- [x] ClimbingRecordService에서 DTO 생성 로직 간소화
- [x] 유저의 위치 기반으로 거리를 계산하는 로직 전반적인 리팩토링
- [ ] 위도, 경도 자료형 double 대신 BigDecimal로 변경

## 🗨️ ETC
OOO

**Comment by lhs8701** [comment]
화이또 🔥
