### ISSUE TITLE
[Feature] 테스트 코드 리팩토링, 산 단건 조회 API 추가, 각종 네이밍 변경

### ISSUE THREAD

**Issue by lhs8701** [ORGO-Official/orgo-backend#45]
## 💡 Description

FE의 요청으로 산 단건 조회 API를 추가합니다. 
지표 행님께서 주신 피드백을 반영합니다.

## ✅ To-do
- [x] 패키지 구조 이름 변경
- [x] RestAssured를 이용한 통합 테스트 코드 추가 
- [x] 기존 컨트롤러 테스트 변경
- [x] 산 단건 조회 API 추가
- [x] LoginFactory 이름 변경
- [x] 인근 식당 조회 API에서 카카오맵 링크가 존재하는 식당만 리턴하도록 변경

## 🗨️ ETC
OOO
