### ISSUE TITLE
[Refactor] 산 별 배경 이미지, 프로필 이미지, 태그, 난이도, 완등 시간 설정

### ISSUE THREAD

**Issue by lhs8701** [ORGO-Official/orgo-backend#51]
## 💡 Description
OOO

## ✅ To-do
- [ ] 산 별 배경 이미지 설정
- [ ] 산 별 프로필 이미지 설정
- [x] 산 별 태그 설정
- [x] 산 별 난이도 설정
- [x] 산 별 완등 시간 설정

## 🗨️ ETC
OOO
