### ISSUE TITLE
[Feature] 뱃지 테이블 생성 및 데이터 추가 

### ISSUE THREAD

**Issue by lhs8701** [ORGO-Official/orgo-backend#54]
## 💡 Description
보유한 뱃지 조회 기능을 구현하기 전, 필요한 테이블 및 클래스를 설계하고, 더미데이터를 추가합니다. 

## ✅ To-do
- [x] 뱃지  슈퍼테이블 추가
- [x] 완등 기록 뱃지 테이블 추가
- [x] 완등 높이 뱃지 테이블 추가
- [x] 완등 년월 뱃지 테이블 추가  
- [x] 더미 데이터 추가

## 🗨️ ETC
OOO
