### ISSUE TITLE
[Feature] 획득/미획득 뱃지 조회 기능 구현

### ISSUE THREAD

**Issue by lhs8701** [ORGO-Official/orgo-backend#56]
## 💡 Description
사용자가 보유한 뱃지 목록을 조회할 수 있도록 기능을 구현합니다. 

## ✅ To-do
- [x] Acquisition 엔티티 추가
- [x] Badge 엔티티의 check() 메서드 추가
- [x] Badge 엔티티의 issue() 추상 메서드 추가
- [x] 획득한 뱃지 조회 API 구현
- [x] 획득/미획득 뱃지 조회 API 구현

## 🗨️ ETC
OOO
