### ISSUE TITLE
[Setting] 프로젝트 셋업

### ISSUE THREAD

**Issue by lhs8701** [ORGO-Official/orgo-backend#6]
## 💡 Description
프로젝트 진행에 앞서, 기본 설정을 수행한다. 

## ✅ To-do
- [x] start.spring.io를 통해 프로젝트 생성
- [x] 기본 의존성 주입
- [x] 프로필 분리 
- [x] DB 연결
- [x] RestDocs 설정
- [x] 패키지 구조 설정

## 🗨️ ETC
- 기본 설정과 관련된 부분이라, 따로 PR을 생성하지 않음. main 브랜치에서 바로 확인하면 될 듯.
- @lhs8701 의 3306 포트가 MariaDB로 연결되어 있으나, @devMuscle 은 그렇지 않을 확률 큼. 필요 시 포트 변경 예정.
- 통합 테스트 및 RestDocs 사용에 익숙해져야 함.
