### ISSUE TITLE
백엔드 기획 문서 작성

### ISSUE THREAD

**Issue by lhs8701** [ORGO-Official/orgo-backend#8]
## 💡 Description
개발에 필요한 기획 문서 작성

## ✅ To-do
- [x] ERD 작성
- [ ] API 명세서 작성
- [ ] Git-flow 매뉴얼 작성
- [x] 코드 컨벤션 작성

## 🗨️ ETC
화이팅 !

### ERD
https://www.notion.so/DB-642a6ef276934805acbd80a018fbf7ef?pvs=4

### API 명세
https://www.notion.so/78d3aeb6a32d4ffa86482e98328ddd30?v=39acd33a8a5a42eab5eeb48cdc69bbbd

### 코드 컨벤션
https://www.notion.so/051daef82da34f82ad94fce98eba2147
